package config

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func IncludesGitconfigPath() string { return filepath.Join(ConfigDir(), "includes.gitconfig") }
func DefaultGitconfigPath() string  { return filepath.Join(ConfigDir(), "default.gitconfig") }

// Reconcile regenerates all derived Git artifacts from authoritative YAML.
func (c *Config) Reconcile() error {
	if err := c.Validate(); err != nil {
		return err
	}
	if err := os.MkdirAll(profilesDir, dirPermissions); err != nil {
		return fmt.Errorf("create profiles directory: %w", err)
	}
	names := make([]string, 0, len(c.Profiles))
	for name := range c.Profiles {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		if err := EnsureProfileGitconfig(name, c.Profiles[name]); err != nil {
			return fmt.Errorf("generate profile %q: %w", name, err)
		}
	}
	entries, err := os.ReadDir(profilesDir)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".gitconfig") {
			continue
		}
		name := strings.TrimSuffix(entry.Name(), ".gitconfig")
		if _, ok := c.Profiles[name]; !ok {
			if err := os.Remove(filepath.Join(profilesDir, entry.Name())); err != nil {
				return err
			}
		}
	}
	if err := c.writeDefault(); err != nil {
		return err
	}
	if err := c.writeIncludes(); err != nil {
		return err
	}
	if err := reconcileGlobalGitconfig(); err != nil {
		return err
	}
	return nil
}

func (c *Config) writeDefault() error {
	if c.ActiveProfile == "" {
		return atomicWriteFile(DefaultGitconfigPath(), nil, filePermissions)
	}
	path, err := ProfileGitconfigPath(c.ActiveProfile)
	if err != nil {
		return err
	}
	quoted, err := quoteGitConfigValue(filepath.ToSlash(path))
	if err != nil {
		return err
	}
	return atomicWriteFile(DefaultGitconfigPath(), []byte("[include]\n    path = "+quoted+"\n"), filePermissions)
}

func (c *Config) writeIncludes() error {
	defaultPath, _ := quoteGitConfigValue(filepath.ToSlash(DefaultGitconfigPath()))
	var b strings.Builder
	b.WriteString("# Generated by git-ego. Changes will be overwritten.\n[include]\n    path = ")
	b.WriteString(defaultPath)
	b.WriteByte('\n')
	for _, rule := range c.SortedAutoRules() {
		profilePath, err := ProfileGitconfigPath(rule.Profile)
		if err != nil {
			return err
		}
		condition, err := quoteGitConfigValue("gitdir:" + rule.Path)
		if err != nil {
			return err
		}
		path, err := quoteGitConfigValue(filepath.ToSlash(profilePath))
		if err != nil {
			return err
		}
		fmt.Fprintf(&b, "\n[includeIf %s]\n    path = %s\n", condition, path)
	}
	return atomicWriteFile(IncludesGitconfigPath(), []byte(b.String()), filePermissions)
}

func reconcileGlobalGitconfig() error {
	data, err := os.ReadFile(gitConfigPath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read global gitconfig: %w", err)
	}
	blocks := splitGitConfigBlocks(string(data))
	kept := make([]string, 0, len(blocks)+1)
	managed := map[string]bool{
		filepath.ToSlash(IncludesGitconfigPath()): true,
		filepath.ToSlash(DefaultGitconfigPath()):  true,
	}
	for _, block := range blocks {
		path := blockPath(block)
		isLegacyProfile := path != "" && strings.HasSuffix(filepath.Base(path), ".gitconfig") && filepath.Dir(filepath.Clean(path)) == filepath.Clean(profilesDir)
		if managed[filepath.ToSlash(path)] || isLegacyProfile {
			continue
		}
		kept = append(kept, block)
	}
	quoted, _ := quoteGitConfigValue(filepath.ToSlash(IncludesGitconfigPath()))
	kept = append(kept, "# git-ego managed include (keep last)\n[include]\n    path = "+quoted+"\n")
	output := strings.TrimSpace(strings.Join(kept, "\n")) + "\n"
	return atomicWriteFile(gitConfigPath, []byte(output), filePermissions)
}

func splitGitConfigBlocks(input string) []string {
	lines := strings.Split(input, "\n")
	var blocks []string
	start := 0
	for i, line := range lines {
		if i > 0 && strings.HasPrefix(strings.TrimSpace(line), "[") {
			blocks = append(blocks, strings.Join(lines[start:i], "\n"))
			start = i
		}
	}
	if start < len(lines) {
		blocks = append(blocks, strings.Join(lines[start:], "\n"))
	}
	return blocks
}

func blockPath(block string) string {
	lines := strings.Split(block, "\n")
	header := ""
	for _, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), "[") {
			header = strings.ToLower(strings.TrimSpace(line))
			break
		}
	}
	if !strings.HasPrefix(header, "[include") {
		return ""
	}
	for _, line := range lines {
		key, value, ok := strings.Cut(strings.TrimSpace(line), "=")
		if ok && strings.EqualFold(strings.TrimSpace(key), "path") {
			return strings.Trim(strings.TrimSpace(value), "\"")
		}
	}
	return ""
}
